// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotations } from "./Annotations";

/**
 * Audio provided to or from an LLM.
 */
export type AudioContent = { annotations?: Annotations, data: string, mimeType: string, type: string, };
