// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionCallOutputContentItem } from "./FunctionCallOutputContentItem";

/**
 * The payload we send back to OpenAI when reporting a tool call result.
 *
 * `content` preserves the historical plain-string payload so downstream
 * integrations (tests, logging, etc.) can keep treating tool output as
 * `String`. When an MCP server returns richer data we additionally populate
 * `content_items` with the structured form that the Responses/Chat
 * Completions APIs understand.
 */
export type FunctionCallOutputPayload = { content: string, content_items: Array<FunctionCallOutputContentItem> | null, success: boolean | null, };
