import * as React from 'react'
import type { ComponentEntry } from './types'
import { generateCallbackPage, type AppType } from '@agent-operator/shared/auth/callback-page'

/**
 * Preview component that renders OAuth callback HTML in a sandboxed iframe.
 * The HTML is generated by the same function used in the actual OAuth flow,
 * allowing us to preview the success/error states without triggering real OAuth.
 */
function OAuthCallbackPreview({
  isSuccess,
  errorDetail,
  appType,
}: {
  isSuccess: boolean
  errorDetail?: string
  appType: AppType
}) {
  const html = React.useMemo(() => {
    return generateCallbackPage({
      title: isSuccess ? 'Authorization Complete' : 'Authorization Failed',
      isSuccess,
      errorDetail,
      appType,
    })
  }, [isSuccess, errorDetail, appType])

  return (
    <iframe
      srcDoc={html}
      sandbox="allow-scripts"
      className="w-full h-full border-0"
      title="OAuth Callback Preview"
    />
  )
}

export const oauthComponents: ComponentEntry[] = [
  {
    id: 'oauth-callback',
    name: 'OAuth Callback Page',
    category: 'OAuth',
    description: 'Page shown in browser after OAuth authorization redirect',
    component: OAuthCallbackPreview,
    layout: 'full',
    props: [
      {
        name: 'isSuccess',
        description: 'Whether authorization was successful',
        control: { type: 'boolean' },
        defaultValue: true,
      },
      {
        name: 'appType',
        description: 'App type (electron or terminal)',
        control: {
          type: 'select',
          options: [
            { label: 'Electron', value: 'electron' },
            { label: 'Terminal', value: 'terminal' },
          ],
        },
        defaultValue: 'electron',
      },
      {
        name: 'errorDetail',
        description: 'Error message (only shown when isSuccess is false)',
        control: { type: 'string', placeholder: 'Error message' },
        defaultValue: '',
      },
    ],
    variants: [
      // Success states
      {
        name: 'Success',
        props: { isSuccess: true, appType: 'electron' },
      },
      // Error states
      {
        name: 'Error - Access Denied',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The user denied the authorization request.',
        },
      },
      {
        name: 'Error - Invalid Scope',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The requested scope is invalid or unknown.',
        },
      },
      {
        name: 'Error - Server Error',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The authorization server encountered an unexpected condition.',
        },
      },
      {
        name: 'Error - Expired Token',
        props: {
          isSuccess: false,
          appType: 'electron',
          errorDetail: 'The authorization code has expired.',
        },
      },
      {
        name: 'Error - Generic',
        props: {
          isSuccess: false,
          appType: 'electron',
        },
      },
    ],
    mockData: () => ({
      isSuccess: true,
      appType: 'electron',
    }),
  },
]
