// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfo = { id: string, name: string, description: string | null, logoUrl: string | null, installUrl: string | null, isAccessible: boolean, };
