// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillInterface } from "./SkillInterface";
import type { SkillScope } from "./SkillScope";

export type SkillMetadata = { name: string, description: string, 
/**
 * Legacy short_description from SKILL.md. Prefer SKILL.toml interface.short_description.
 */
shortDescription?: string, interface?: SkillInterface, path: string, scope: SkillScope, enabled: boolean, };
