// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSortKey } from "./ThreadSortKey";

export type ThreadListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor: string | null, 
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit: number | null, 
/**
 * Optional sort key; defaults to created_at.
 */
sortKey: ThreadSortKey | null, 
/**
 * Optional provider filter; when set, only sessions recorded under these
 * providers are returned. When present but empty, includes all providers.
 */
modelProviders: Array<string> | null, 
/**
 * Optional archived filter; when set to true, only archived threads are returned.
 * If false or null, only non-archived threads are returned.
 */
archived: boolean | null, };
